name: Clic Automático Diario

on:
  schedule:
    # Define la hora en formato UTC (Ejemplo: 14:00 UTC)
    # El formato es: Minuto Hora Día Mes Día_de_la_semana
    - cron: "30 20 * * *"
  workflow_dispatch: # Permite ejecutarlo manualmente para probar

jobs:
  ejecutar-clic:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar dependencias
        run: |
          pip install selenium webdriver-manager

      - name: Ejecutar script de clic
        run: python script.py
